// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: user.proto

package pb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// UserServiceService defines service.
type UserServiceService interface {
	GetUserById(ctx context.Context, req *UserRequest) (*UserResponse, error)
}

func UserServiceService_GetUserById_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserServiceService).GetUserById(ctx, reqbody.(*UserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// UserServiceServer_ServiceDesc descriptor for server.RegisterService.
var UserServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "edu.imau.pb.UserService",
	HandlerType: ((*UserServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/edu.imau.pb.UserService/GetUserById",
			Func: UserServiceService_GetUserById_Handler,
		},
	},
}

// RegisterUserServiceService registers service.
func RegisterUserServiceService(s server.Service, svr UserServiceService) {
	if err := s.Register(&UserServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("UserService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedUserService struct{}

func (s *UnimplementedUserService) GetUserById(ctx context.Context, req *UserRequest) (*UserResponse, error) {
	return nil, errors.New("rpc GetUserById of service UserService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// UserServiceClientProxy defines service client proxy
type UserServiceClientProxy interface {
	GetUserById(ctx context.Context, req *UserRequest, opts ...client.Option) (rsp *UserResponse, err error)
}

type UserServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewUserServiceClientProxy = func(opts ...client.Option) UserServiceClientProxy {
	return &UserServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *UserServiceClientProxyImpl) GetUserById(ctx context.Context, req *UserRequest, opts ...client.Option) (*UserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/edu.imau.pb.UserService/GetUserById")
	msg.WithCalleeServiceName(UserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("UserService")
	msg.WithCalleeMethod("GetUserById")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
